version: "3.7"

networks:
  backend:

services:
  client:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./client/docker/Dockerfile
    container_name: client
    ports:
      - ${CLIENT_PORT}:3000
    volumes:
      - "./client/:/app/"
    depends_on:
      - server

  server:
    env_file: 
      - .env
    build:
      context: .
      dockerfile: ./server/docker/Dockerfile
    container_name: server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - backend
    volumes:
      - "./server/:/app/"
    depends_on:
      - db

  db:
    env_file: 
      - .env
    image: mongo:latest
    container_name: db
    restart: always
    networks:
      - backend
    volumes:
      - "./db:/data/db"
      - "./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro"
