version: "3.7"

networks:
  backend:
  frontend:

services:
  proxy:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./proxy/DockerFile
    container_name: proxy
    restart: always
    ports:
      - "${CLIENT_PORT}:80"
    networks:
      - frontend
  client:
    env_file:
      - .env
    environment:
      - REACT_APP_API_URL=${SERVER_URL}:${CLIENT_PORT}/api
    build:
      context: .
      dockerfile: ./client/docker/Dockerfile
    container_name: client
    networks:
      - frontend
    volumes:
      - ./client/:/app/
      - /app/node_modules
    depends_on:
      - server

  server:
    env_file: 
      - .env
    build:
      context: .
      dockerfile: ./server/docker/Dockerfile
    container_name: server
    networks:
      - frontend
      - backend
    volumes:
      - ./server/:/app/
      - /app/node_modules
    depends_on:
      - db

  db:
    env_file: 
      - .env
    image: mariadb:latest
    container_name: db
    restart: always
    networks:
      - backend
    volumes:
      - "./db:/data/db"
      - "./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro"
