version: "3.7"

networks:
  backend:
  frontend:

services:
  proxy:
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./proxy/DockerFile
    container_name: proxy
    volumes:
      - ./certs/:/etc/nginx/ssl
    ports:
      - "${SERVER_PORT}:443"
    networks:
      - frontend
  client:
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REACT_APP_API_URL=https://${SERVER_URL}:${SERVER_PORT}/api
      - REACT_APP_WS_URL=wss://${SERVER_URL}:${SERVER_PORT}/api
    build:
      context: .
      dockerfile: ./client/docker/Dockerfile
    container_name: client
    networks:
      - frontend
    volumes:
      - ./client/:/app/
      - /app/node_modules
    depends_on:
      - server

  server:
    restart: unless-stopped
    env_file: 
      - .env
    build:
      context: .
      dockerfile: ./server/docker/Dockerfile
    container_name: server
    networks:
      - frontend
      - backend
    volumes:
      - ./server/:/app/
      - /app/node_modules
    depends_on:
      - db
  db:
    restart: unless-stopped
    env_file: 
      - .env
    image: mariadb:latest
    container_name: db
    networks:
      - backend
    volumes:
      - "./db:/data/db"
      - "./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro"
