# nginx-proxy/Dockerfile
FROM nginx:alpine

COPY ./proxy/nginx.conf /etc/nginx/nginx.conf.template

EXPOSE 80

CMD ["/bin/sh", "-c", "envsubst '$$SERVER_PORT,$$CLIENT_PORT' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf.temp && mv /etc/nginx/nginx.conf.temp /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]